let cartasJson = [
    {id:1,nome:'Brasil',img:'/img/brasil.png'},
    {id:2,nome:'Bolivia',img:'/img/bolivia.png'},
    {id:3,nome:'Paraguai',img:'/img/paraguai.png'},
    {id:4,nome:'Panama',img:'/img/panama.png'},
    {id:5,nome:'Mexico',img:'/img/mexico.png'},
    {id:6,nome:'Estados Unidos',img:'/img/eua.png'},
    {id:7,nome:'Cuba',img:'/img/cuba.png'},
    {id:8,nome:'Chile',img:'/img/chile.png'},
    {id:9,nome:'Argentina',img:'/img/argentina.png'},
    {id:10,nome:'Peru',img:'/img/peru.png'},
    {id:11,nome:'Portugal',img:'/img/portugal.png'},
    {id:12,nome:'Venezuela',img:'/img/venezuela.png'},
    {id:13,nome:'Brasil',img:'/img/brasil.png'},
    {id:14,nome:'Bolivia',img:'/img/bolivia.png'},
    {id:15,nome:'Paraguai',img:'/img/paraguai.png'},
    {id:24,nome:'Panama',img:'/img/panama.png'},
    {id:23,nome:'Mexico',img:'/img/mexico.png'},
    {id:16,nome:'Estados Unidos',img:'/img/eua.png'},
    {id:17,nome:'Cuba',img:'/img/cuba.png'},
    {id:18,nome:'Chile',img:'/img/chile.png'},
    {id:19,nome:'Argentina',img:'/img/argentina.png'},
    {id:20,nome:'Peru',img:'/img/peru.png'},
    {id:21,nome:'Portugal',img:'/img/portugal.png'},
    {id:22,nome:'Venezuela',img:'/img/venezuela.png'}
]